// Expanded Spring card database. Five non-duplicated questions are chosen per game.
const springFoods = [
  {name:"Zucchini Flower",image:"zucchini-flower.png",origin:"Italy",grows:"On a vine, above the ground",clue:"This edible yellow flower grows on a zucchini plant.",group:"zucchini"},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine, above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks, above the ground",clue:"Its sweet yellow kernels grow together on a cob."},
  {name:"Peas",image:"peas.png",origin:"Turkey",grows:"Inside pods on climbing vines",clue:"These small green seeds grow together inside a pod."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine, above the ground",clue:"This long green vegetable is also called courgette.",group:"zucchini"},
  {name:"Watercress",image:"watercress.png",origin:"England",grows:"In shallow, flowing water",clue:"This peppery leafy green naturally grows beside clean streams."},
  {name:"Shallot",image:"shallot.png",origin:"Iran",grows:"As a bulb underground",clue:"This small bulb tastes milder and sweeter than an onion.",group:"onion"},
  {name:"Spring Onion",image:"spring-onion.png",origin:"China",grows:"As a small bulb underground with leaves above",clue:"This onion has a long green top and a slender white base.",group:"onion"},
  {name:"Mushrooms",image:"mushrooms.png",origin:"France",grows:"From fungal networks in soil or compost",clue:"This food is a fungus and often has a cap and a stem."},
  {name:"Globe Artichoke",image:"globe-artichoke.png",origin:"Italy",grows:"As a flower bud above the ground",clue:"We eat the unopened flower bud and the soft heart inside."},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is a common base for salads."},
  {name:"Garlic",image:"garlic.png",origin:"Kazakhstan",grows:"As a bulb underground",clue:"This strong-smelling bulb is made of several cloves."},
  {name:"Chillies",image:"chillies.png",origin:"Mexico",grows:"On a small bush above the ground",clue:"These colourful peppers can make food taste very hot."},
  {name:"Green Beans",image:"green-beans.png",origin:"Mexico",grows:"In pods on climbing or bushy plants",clue:"The long green pod is eaten while it is still young.",group:"beans"},
  {name:"Broad Beans",image:"broad-beans.png",origin:"Egypt",grows:"Inside thick pods above the ground",clue:"These large, flat beans are also known as fava beans.",group:"beans"},
  {name:"Asian Greens",image:"asian-greens.png",origin:"China",grows:"As leafy plants above the ground",clue:"This group includes leafy vegetables such as bok choy."},
  {name:"Asparagus",image:"asparagus.png",origin:"Greece",grows:"As spears rising from underground crowns",clue:"Its tender green spears push straight up through the soil."},
  {name:"Beetroot",image:"beetroot.png",origin:"Italy",grows:"As a swollen root underground",clue:"This deep red root can stain your hands when it is cut."},
  {name:"Carrots",image:"carrots.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
  {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
  {name:"Potatoes",image:"potatoes.png",origin:"Peru",grows:"As tubers underground",clue:"These starchy tubers grow beneath the soil."},
  {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"},
  {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft, dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping vine above the ground",clue:"This cool, crisp food has watery flesh and is often sliced for salads."},
  {name:"Green Onion",image:"green-onion.png",origin:"China",grows:"As a small bulb underground with leaves above",clue:"Its long green leaves have a mild onion flavour.",group:"onion"},
  {name:"Loquat",image:"loquat.png",origin:"China",grows:"In clusters on a tree",clue:"This small orange fruit has several large brown seeds."},
  {name:"Cherries",image:"cherries.png",origin:"Turkey",grows:"On a tree",clue:"These small stone fruits often grow in pairs on long stems."},
  {name:"Boysenberry",image:"boysenberry.png",origin:"United States",grows:"On trailing canes above the ground",clue:"This dark berry is a hybrid related to raspberries and blackberries.",group:"cane-berries"},
  {name:"Blackberry",image:"blackberry.png",origin:"United Kingdom",grows:"On thorny canes above the ground",clue:"This dark fruit is made of many small juicy sections.",group:"cane-berries"},
  {name:"Passionfruit",image:"passionfruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its wrinkled skin are many seeds in fragrant pulp."},
  {name:"Melon",image:"melon.png",origin:"Iran",grows:"On a creeping vine along the ground",clue:"This sweet round fruit has juicy flesh and many seeds in the centre.",group:"melon"},
  {name:"Mango",image:"mango.png",origin:"India",grows:"On a tree",clue:"This tropical fruit has sweet golden flesh around one large stone."},
  {name:"Blueberry",image:"blueberry.png",origin:"United States",grows:"In clusters on a bush",clue:"These small blue fruits grow together on shrubs."},
  {name:"Rockmelon",image:"rockmelon.png",origin:"Iran",grows:"On a creeping vine along the ground",clue:"This melon has netted skin and sweet orange flesh.",group:"melon"},
  {name:"Pineapple",image:"pineapple.png",origin:"Brazil",grows:"On a low plant above the ground",clue:"This tropical fruit has spiky leaves and rough patterned skin."},
  {name:"Papaw",image:"papaw.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"In Australia, this is a common name for the large tropical papaya.",group:"papaya"},
  {name:"Papaya",image:"papaya.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"This tropical fruit has orange flesh and many black seeds.",group:"papaya"},
  {name:"Mulberry",image:"mulberry.png",origin:"China",grows:"On a tree",clue:"This long, bumpy berry grows on the same tree loved by silkworms."},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
  {name:"Grapefruit",image:"grapefruit-1.png",origin:"Barbados",grows:"On a tree",clue:"This large citrus fruit can taste both tart and slightly bitter."},
  {name:"Apples",image:"apples.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp round fruit grows on a deciduous tree."},
  {name:"Lemons",image:"lemons.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice."},
  {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat this vegetable's green stalk and tightly packed flower buds.",group:"brassica-head"},
  {name:"Mandarins",image:"mandarins.png",origin:"China",grows:"On a tree",clue:"This small citrus fruit has loose skin that is easy to peel.",group:"citrus"},
  {name:"Oranges",image:"oranges.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
  {name:"Pomelo",image:"pomelo.png",origin:"Malaysia",grows:"On a tree",clue:"This is the largest citrus fruit and has a very thick rind.",group:"citrus"},
  {name:"Strawberry",image:"strawberry.png",origin:"France",grows:"On low plants close to the ground",clue:"This red fruit carries its tiny seeds on the outside."},
  {name:"Tangelos",image:"tangelos.png",origin:"United States",grows:"On a tree",clue:"This citrus is a cross between a mandarin and a grapefruit or pomelo.",group:"citrus"},
  {name:"Blood Orange",image:"blood-orange.png",origin:"Italy",grows:"On a tree",clue:"This orange has unusually deep red flesh inside.",group:"citrus"}
].map(food => ({...food, image: `assets/cards/spring/${food.image}`}));

// Expanded Summer card database. The supplied set contains 42 unique card files.
// The two Passion Fruit designs share one group, so they never appear together in one game.
const summerFoods = [
  {name:"Blackberry",image:"blackberry.png",origin:"United Kingdom",grows:"On thorny canes above the ground",clue:"This dark berry is made of many small juicy sections.",group:"cane-berries"},
  {name:"Blueberry",image:"blueberry.png",origin:"United States",grows:"In clusters on a bush",clue:"These small blue fruits grow in clusters on woody shrubs."},
  {name:"Passion Fruit",image:"passion-fruit-1.png",origin:"Brazil",grows:"On a climbing vine",clue:"This fragrant tropical fruit contains many seeds in juicy pulp.",group:"passion-fruit"},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Passion Fruit",image:"passion-fruit-2.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its thick skin are many crunchy seeds surrounded by fragrant pulp.",group:"passion-fruit"},
  {name:"Berries",image:"berries.png",origin:"France",grows:"On low plants or canes above the ground",clue:"This card shows a mixed group of small, colourful, juicy fruits.",group:"cane-berries"},
  {name:"Rambutans",image:"rambutans.png",origin:"Malaysia",grows:"In clusters on a tropical tree",clue:"These tropical fruits have red skin covered with soft hair-like spines."},
  {name:"Prickly Pears",image:"prickly-pears.png",origin:"Mexico",grows:"On the pads of a cactus",clue:"These fruits grow on a cactus and must be handled carefully because of tiny spines."},
  {name:"Plums",image:"plums.png",origin:"China",grows:"On a tree",clue:"These smooth-skinned stone fruits can be purple, red, yellow or green.",group:"stone-fruit"},
  {name:"Peach",image:"peach.png",origin:"China",grows:"On a tree",clue:"This sweet stone fruit is famous for its soft, fuzzy skin.",group:"stone-fruit"},
  {name:"Nectarines",image:"nectarines.png",origin:"China",grows:"On a tree",clue:"These stone fruits resemble peaches but have smooth skin.",group:"stone-fruit"},
  {name:"Mangosteens",image:"mangosteens.png",origin:"Indonesia",grows:"On a tropical evergreen tree",clue:"A thick purple rind protects the soft white segments inside."},
  {name:"Lychees",image:"lychees.png",origin:"China",grows:"In clusters on an evergreen tree",clue:"These small fruits have rough red skin and translucent white flesh."},
  {name:"Limes",image:"limes.png",origin:"Malaysia",grows:"On a small citrus tree",clue:"These small green citrus fruits have sharply sour juice."},
  {name:"Raspberry",image:"raspberry.png",origin:"Turkey",grows:"On thorny or bristly canes above the ground",clue:"This soft berry is made of many tiny red sections and has a hollow centre.",group:"cane-berries"},
  {name:"Grapes",image:"grapes.png",origin:"Georgia",grows:"In bunches on a woody vine",clue:"These round fruits grow together in bunches and can be dried into raisins."},
  {name:"Figs",image:"figs.png",origin:"Turkey",grows:"On a tree",clue:"This soft fruit has many tiny seeds and a sweet, jam-like centre."},
  {name:"Currants",image:"currants.png",origin:"Netherlands",grows:"In strings of small berries on a bush",clue:"These tiny red, black or white berries hang in clusters from shrubs."},
  {name:"Apricot",image:"apricot.png",origin:"China",grows:"On a tree",clue:"This small orange stone fruit has soft flesh and a slightly tart taste.",group:"stone-fruit"},
  {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant above the ground",clue:"When cut, this long green pod reveals a star shape and many round seeds."},
  {name:"Sweet Onion",image:"sweet-onion.png",origin:"Iran",grows:"As a bulb underground",clue:"This round bulb has a mild flavour and usually causes fewer tears than a strong onion.",group:"onion"},
  {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine or bush above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine above the ground",clue:"This long green summer squash is also called courgette."},
  {name:"Watercress",image:"watercress.png",origin:"England",grows:"In shallow, clean flowing water",clue:"This peppery leafy green naturally grows beside streams."},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks above the ground",clue:"Its sweet yellow kernels grow in rows together on a cob."},
  {name:"Green Onion",image:"green-onion.png",origin:"China",grows:"As a small bulb underground with green leaves above",clue:"This onion has long hollow green leaves and a slender white base.",group:"onion"},
  {name:"Peas",image:"peas.png",origin:"Turkey",grows:"Inside pods on climbing vines",clue:"These small round seeds grow together inside a green pod.",group:"peas"},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is commonly used as the base of a salad."},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping or climbing vine above the ground",clue:"This long green food has cool, watery flesh and many soft seeds."},
  {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks of this plant are the part most often eaten."},
  {name:"Butter Bean",image:"butter-bean.png",origin:"Peru",grows:"Inside pods on a bush or climbing vine",clue:"This large, flat, creamy bean is also known as a lima bean.",group:"beans"},
  {name:"Green Beans",image:"green-beans.png",origin:"Mexico",grows:"In pods on bushy or climbing plants",clue:"The entire long green pod is eaten while it is still young.",group:"beans"},
  {name:"Asparagus",image:"asparagus.png",origin:"Greece",grows:"As spears rising from underground crowns",clue:"Its tender green spears push straight up through the soil."},
  {name:"Squash",image:"squash.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This food grows on a spreading vine and may have a hard or soft rind."},
  {name:"Sugar Snap Peas",image:"sugar-snap-peas.png",origin:"United States",grows:"Inside edible pods on climbing vines",clue:"Both the crisp sweet pod and the round peas inside can be eaten.",group:"peas"},
  {name:"Choko",image:"choko.png",origin:"Mexico",grows:"On a vigorous climbing vine",clue:"This pale green, pear-shaped vegetable is also called chayote."},
  {name:"Snake Beans",image:"snake-beans.png",origin:"India",grows:"As very long pods on climbing vines",clue:"These beans form unusually long, thin pods that can curl like a snake.",group:"beans"},
  {name:"Radish",image:"radish.png",origin:"China",grows:"As a swollen root underground",clue:"This crisp, peppery root is often round and red with leaves above the soil."},
  {name:"Flat Beans",image:"flat-beans.png",origin:"Italy",grows:"As broad pods on climbing or bushy plants",clue:"These beans have wide, flattened pods rather than thin round ones.",group:"beans"},
  {name:"Capsicum",image:"capsicum.png",origin:"Mexico",grows:"As hollow fruits on a small bush",clue:"This mild, hollow pepper can be green, red, yellow or orange."},
  {name:"Eggplant",image:"eggplant.png",origin:"India",grows:"As fruits on a bushy plant above the ground",clue:"This glossy purple vegetable is also known as aubergine."}
].map(food => ({...food, image: `assets/cards/summer/${food.image}`}));

// Expanded Autumn card database. Five non-duplicated questions are chosen per game.
const autumnFoods = [
  {name:"Nashi",image:"nashi.png",origin:"China",grows:"On a tree",clue:"This round Asian pear is crisp and juicy, like an apple.",group:"pear"},
  {name:"Papaw",image:"papaw.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"In Australia, this is a common name for the large tropical papaya."},
  {name:"Persimmon",image:"persimmon.png",origin:"China",grows:"On a tree",clue:"This orange fruit becomes soft and very sweet when fully ripe."},
  {name:"Figs",image:"figs.png",origin:"Turkey",grows:"On a tree",clue:"This soft fruit has many tiny seeds and a sweet, jam-like centre."},
  {name:"Grapes",image:"grapes.png",origin:"Georgia",grows:"In bunches on a woody vine",clue:"These round fruits grow in bunches and can be dried into raisins."},
  {name:"Lime",image:"lime.png",origin:"Malaysia",grows:"On a small citrus tree",clue:"This small green citrus fruit has sharply sour juice.",group:"citrus"},
  {name:"Mangosteen",image:"mangosteen.png",origin:"Indonesia",grows:"On a tropical evergreen tree",clue:"A thick purple rind protects the soft white segments inside."},
  {name:"Plums",image:"plums.png",origin:"China",grows:"On a tree",clue:"These smooth-skinned stone fruits can be purple, red, yellow or green."},
  {name:"Passion Fruit",image:"passion-fruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its thick skin are many seeds in fragrant pulp."},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Pear",image:"pear.png",origin:"Georgia",grows:"On a tree",clue:"This sweet fruit is wider at the bottom and narrower near its stem.",group:"pear"},
  {name:"Orange",image:"orange.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
  {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
  {name:"Custard Apple",image:"custard-apple.png",origin:"Peru",grows:"On a small tropical tree",clue:"This knobbly fruit has soft, creamy flesh with a custard-like texture."},
  {name:"Fuji Fruit",image:"fuji-fruit.png",origin:"Japan",grows:"On an apple tree",clue:"This crisp, sweet apple variety was developed in Japan."},
  {name:"Guava",image:"guava.png",origin:"Mexico",grows:"On a small tropical tree",clue:"This fragrant tropical fruit has many small edible seeds."},
  {name:"Mandarins",image:"mandarins.png",origin:"China",grows:"On a tree",clue:"These small citrus fruits have loose skin that is easy to peel.",group:"citrus"},
  {name:"Kiwifruit",image:"kiwifruit.png",origin:"China",grows:"On a climbing vine",clue:"This fuzzy brown fruit has bright green flesh and tiny black seeds."},
  {name:"Apple",image:"apple.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp round fruit can be red, green or yellow."},
  {name:"Lemon",image:"lemon.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice.",group:"citrus"},
  {name:"Quince",image:"quince.png",origin:"Iran",grows:"On a small tree",clue:"This fragrant yellow fruit looks like a lumpy pear and is usually cooked."},
  {name:"Pomegranate",image:"pomegranate.png",origin:"Iran",grows:"On a shrub or small tree",clue:"Its tough skin hides hundreds of jewel-like juicy seeds."},
  {name:"Rhubarb",image:"rhubarb.png",origin:"China",grows:"As thick stalks above the ground",clue:"Only the crisp stalks of this plant are eaten, usually after cooking."},
  {name:"Tamarillo",image:"tamarillo.png",origin:"Ecuador",grows:"On a small tree",clue:"This egg-shaped fruit is also called a tree tomato."},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is a common base for salads."},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping or climbing vine",clue:"This long green food has cool, watery flesh and many soft seeds."},
  {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks are the part most often eaten."},
  {name:"Carrot",image:"carrot.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
  {name:"Cabbage",image:"cabbage.png",origin:"France",grows:"As a leafy head above the ground",clue:"This leafy vegetable forms a tight round head.",group:"brassica-head"},
  {name:"Brussels Sprouts",image:"brussels-sprouts.png",origin:"Belgium",grows:"As small leafy buds along a tall stalk",clue:"These miniature cabbages grow in rows along a tall stem.",group:"brassica-head"},
  {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
  {name:"Asian Greens",image:"asian-greens.png",origin:"China",grows:"As leafy plants above the ground",clue:"This group includes leafy vegetables such as bok choy."},
  {name:"Ginger",image:"ginger.png",origin:"Southeast Asia",grows:"As a rhizome underground",clue:"This knobbly underground stem has a warm, spicy flavour."},
  {name:"Chestnut",image:"chestnut.png",origin:"Turkey",grows:"On a tree inside a prickly burr",clue:"This glossy brown nut develops inside a very spiky case."},
  {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant",clue:"When cut, this green pod reveals a star shape and many round seeds."},
  {name:"Onion",image:"onion.png",origin:"Iran",grows:"As a bulb underground",clue:"Peeling this layered bulb can make your eyes water.",group:"onion"},
  {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine or bush above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine above the ground",clue:"This long green squash is also called courgette.",group:"squash"},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks above the ground",clue:"Its sweet yellow kernels grow in rows together on a cob."},
  {name:"Pumpkin",image:"pumpkin.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This large orange fruit grows on a vine and is often used in soup or pie.",group:"squash"},
  {name:"Mushrooms",image:"mushrooms.png",origin:"France",grows:"From fungal networks in soil or compost",clue:"This food is a fungus and often has a cap and a stem."},
  {name:"Leek",image:"leek.png",origin:"Turkey",grows:"As a thick stem with leaves above the ground",clue:"This long, mild member of the onion family has layered white and green leaves.",group:"onion"},
  {name:"Fennel",image:"fennel.png",origin:"Italy",grows:"As a swollen bulb at soil level",clue:"This pale bulb has feathery leaves and a fresh anise-like flavour."},
  {name:"Eschalot",image:"eschalot.png",origin:"Iran",grows:"As a bulb underground",clue:"This small bulb tastes milder and sweeter than a large onion.",group:"onion"},
  {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat its green stalk and tightly packed flower buds.",group:"brassica-head"},
  {name:"Beans",image:"beans.png",origin:"Mexico",grows:"Inside pods on bushy or climbing plants",clue:"These seeds develop together inside long pods."},
  {name:"Choko",image:"choko.png",origin:"Mexico",grows:"On a vigorous climbing vine",clue:"This pale green, pear-shaped vegetable is also called chayote."},
  {name:"Capsicum",image:"capsicum.png",origin:"Mexico",grows:"As hollow fruits on a small bush",clue:"This mild hollow pepper can be green, red, yellow or orange."},
  {name:"Eggplant",image:"eggplant.png",origin:"India",grows:"As fruits on a bushy plant",clue:"This glossy purple vegetable is also known as aubergine."},
  {name:"Witlof",image:"witlof.png",origin:"Belgium",grows:"As a tight pale shoot grown from a root",clue:"This pale, slightly bitter leaf is also called Belgian endive."},
  {name:"Turnip",image:"turnip.png",origin:"Afghanistan",grows:"As a swollen root underground",clue:"This round root can have a white body and a purple top."},
  {name:"Sweet Potato",image:"sweet-potato.png",origin:"Peru",grows:"As a storage root underground",clue:"This sweet orange or cream-coloured root grows beneath the soil."},
  {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
  {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"}
].map(food => ({...food, image: `assets/cards/autumn/${food.image}`}));

const quizData = {
  spring: springFoods,
  summer: summerFoods,
  autumn: autumnFoods,
  winter: [
    {name:"Leeks",image:"leeks.png",origin:"Turkey",grows:"As a thick stem with leaves above the ground",clue:"This long, mild member of the onion family has layered white and green leaves.",group:"onion"},
    {name:"Apple",image:"apple.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp fruit grows on a tree and can be red, green or yellow."},
    {name:"Artichoke",image:"artichoke.png",origin:"Italy",grows:"As an unopened flower bud above the ground",clue:"We eat the tender heart and the soft bases of this unopened flower bud."},
    {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
    {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
    {name:"Beetroot",image:"beetroot.png",origin:"Italy",grows:"As a swollen root underground",clue:"This deep red root can stain your hands when it is cut."},
    {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat this vegetable's green stalk and tightly packed flower buds.",group:"brassica-head"},
    {name:"Brussels Sprout",image:"brussels-sprout.png",origin:"Belgium",grows:"As small leafy buds along a tall stalk",clue:"These miniature cabbages grow in rows along a tall stem.",group:"brassica-head"},
    {name:"Cabbage",image:"cabbage.png",origin:"France",grows:"As a leafy head above the ground",clue:"This leafy vegetable forms a tight round head and is often used in slaws and soups.",group:"brassica-head"},
    {name:"Carrot",image:"carrot.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
    {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
    {name:"Celeriac",image:"celeriac.png",origin:"Italy",grows:"As a swollen stem just below the soil",clue:"This knobbly pale root has a celery-like flavour."},
    {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks of this plant are the part most often eaten."},
    {name:"Cumquat",image:"cumquat.png",origin:"China",grows:"On a small citrus tree",clue:"This tiny oval citrus fruit can be eaten whole, including its sweet peel.",group:"citrus"},
    {name:"Custard Apple",image:"custard-apple.png",origin:"Peru",grows:"On a small tropical tree",clue:"This knobbly fruit has soft, creamy flesh with a custard-like texture."},
    {name:"Fennel",image:"fennel.png",origin:"Italy",grows:"As a swollen bulb at soil level",clue:"This pale bulb has feathery leaves and a fresh anise-like flavour."},
    {name:"Grapefruit",image:"grapefruit.png",origin:"Barbados",grows:"On a tree",clue:"This large citrus fruit can taste both tart and slightly bitter.",group:"citrus"},
    {name:"Jerusalem Artichokes",image:"jerusalem-artichokes.png",origin:"Canada",grows:"As tubers underground",clue:"These knobbly underground tubers are unrelated to globe artichokes."},
    {name:"Kiwi",image:"kiwi.png",origin:"China",grows:"On a climbing vine",clue:"This fuzzy brown fruit has bright green flesh and many tiny black seeds."},
    {name:"Kohlrabi",image:"kohlrabi.png",origin:"Germany",grows:"As a swollen stem above the soil",clue:"This round vegetable is a swollen stem with leaves sprouting from it."},
    {name:"Sweet Potato",image:"sweet-potato.png",origin:"Peru",grows:"As a storage root underground",clue:"This sweet orange or cream-coloured root grows beneath the soil."},
    {name:"Lemon",image:"lemon.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice.",group:"citrus"},
    {name:"Mandarin",image:"mandarin.png",origin:"China",grows:"On a tree",clue:"This small citrus fruit has loose skin that is easy to peel.",group:"citrus"},
    {name:"Nashi",image:"nashi.png",origin:"China",grows:"On a tree",clue:"This round Asian pear is crisp and juicy, like an apple."},
    {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant above the ground",clue:"When cut, this long green pod reveals a star shape and many round seeds."},
    {name:"Olives",image:"olives.png",origin:"Turkey",grows:"In clusters on an evergreen tree",clue:"These small fruits grow on trees and are pressed to make oil."},
    {name:"Onion",image:"onion.png",origin:"Iran",grows:"As a bulb underground",clue:"Peeling this layered bulb can make your eyes water.",group:"onion"},
    {name:"Parsnip",image:"parsnip.png",origin:"Italy",grows:"As a tapered root underground",clue:"This pale root looks like a carrot but has a sweeter, nuttier flavour."},
    {name:"Passion Fruit",image:"passion-fruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its wrinkled skin are many seeds in fragrant pulp."},
    {name:"Pear",image:"pear.png",origin:"Georgia",grows:"On a tree",clue:"This sweet fruit is wider at the bottom and narrower near its stem."},
    {name:"Pomelo",image:"pomelo.png",origin:"Malaysia",grows:"On a tree",clue:"This is the largest citrus fruit and has a very thick rind.",group:"citrus"},
    {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
    {name:"Pumpkin",image:"pumpkin.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This large orange fruit grows on a vine and is often used in soup or pie."},
    {name:"Quince",image:"quince.png",origin:"Iran",grows:"On a small tree",clue:"This fragrant yellow fruit looks like a lumpy pear and is usually cooked."},
    {name:"Rhubarb",image:"rhubarb.png",origin:"China",grows:"As thick stalks above the ground",clue:"Only the crisp stalks of this plant are eaten, usually after cooking."},
    {name:"Orange",image:"orange.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
    {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"},
    {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft, dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
    {name:"Strawberry",image:"strawberry.png",origin:"France",grows:"On low plants close to the ground",clue:"This red fruit carries its tiny seeds on the outside."},
    {name:"Swede",image:"swede.png",origin:"Sweden",grows:"As a swollen root underground",clue:"This round yellow-fleshed root is also called rutabaga."},
    {name:"Turnip",image:"turnip.png",origin:"Afghanistan",grows:"As a swollen root underground",clue:"This round root can have a white body and a purple top."},
    {name:"Witlof",image:"witlof.png",origin:"Belgium",grows:"As a tight pale shoot grown from a root",clue:"This pale, slightly bitter leaf is also called Belgian endive."},
    {name:"Tangelos",image:"tangelos.png",origin:"United States",grows:"On a tree",clue:"This citrus is a cross between a mandarin and a grapefruit or pomelo.",group:"citrus"}
  ].map(food => ({...food, image: `assets/cards/winter/${food.image}`}))
};
