window.YUMMY_QUESTIONS = window.YUMMY_QUESTIONS || {};

window.YUMMY_QUESTIONS.autumn = [
     {name:"Nashi",image:"nashi.png",origin:"China",grows:"On a tree",clue:"This round Asian pear is crisp and juicy, like an apple.",group:"pear"},
  {name:"Papaw",image:"papaw.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"In Australia, this is a common name for the large tropical papaya."},
  {name:"Persimmon",image:"persimmon.png",origin:"China",grows:"On a tree",clue:"This orange fruit becomes soft and very sweet when fully ripe."},
  {name:"Figs",image:"figs.png",origin:"Turkey",grows:"On a tree",clue:"This soft fruit has many tiny seeds and a sweet, jam-like centre."},
  {name:"Grapes",image:"grapes.png",origin:"Georgia",grows:"In bunches on a woody vine",clue:"These round fruits grow in bunches and can be dried into raisins."},
  {name:"Lime",image:"lime.png",origin:"Malaysia",grows:"On a small citrus tree",clue:"This small green citrus fruit has sharply sour juice.",group:"citrus"},
  {name:"Mangosteen",image:"mangosteen.png",origin:"Indonesia",grows:"On a tropical evergreen tree",clue:"A thick purple rind protects the soft white segments inside."},
  {name:"Plums",image:"plums.png",origin:"China",grows:"On a tree",clue:"These smooth-skinned stone fruits can be purple, red, yellow or green."},
  {name:"Passion Fruit",image:"passion-fruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its thick skin are many seeds in fragrant pulp."},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Pear",image:"pear.png",origin:"Georgia",grows:"On a tree",clue:"This sweet fruit is wider at the bottom and narrower near its stem.",group:"pear"},
  {name:"Orange",image:"orange.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
  {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
  {name:"Custard Apple",image:"custard-apple.png",origin:"Peru",grows:"On a small tropical tree",clue:"This knobbly fruit has soft, creamy flesh with a custard-like texture."},
  {name:"Fuji Fruit",image:"fuji-fruit.png",origin:"Japan",grows:"On an apple tree",clue:"This crisp, sweet apple variety was developed in Japan."},
  {name:"Guava",image:"guava.png",origin:"Mexico",grows:"On a small tropical tree",clue:"This fragrant tropical fruit has many small edible seeds."},
  {name:"Mandarins",image:"mandarins.png",origin:"China",grows:"On a tree",clue:"These small citrus fruits have loose skin that is easy to peel.",group:"citrus"},
  {name:"Kiwifruit",image:"kiwifruit.png",origin:"China",grows:"On a climbing vine",clue:"This fuzzy brown fruit has bright green flesh and tiny black seeds."},
  {name:"Apple",image:"apple.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp round fruit can be red, green or yellow."},
  {name:"Lemon",image:"lemon.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice.",group:"citrus"},
  {name:"Quince",image:"quince.png",origin:"Iran",grows:"On a small tree",clue:"This fragrant yellow fruit looks like a lumpy pear and is usually cooked."},
  {name:"Pomegranate",image:"pomegranate.png",origin:"Iran",grows:"On a shrub or small tree",clue:"Its tough skin hides hundreds of jewel-like juicy seeds."},
  {name:"Rhubarb",image:"rhubarb.png",origin:"China",grows:"As thick stalks above the ground",clue:"Only the crisp stalks of this plant are eaten, usually after cooking."},
  {name:"Tamarillo",image:"tamarillo.png",origin:"Ecuador",grows:"On a small tree",clue:"This egg-shaped fruit is also called a tree tomato."},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is a common base for salads."},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping or climbing vine",clue:"This long green food has cool, watery flesh and many soft seeds."},
  {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks are the part most often eaten."},
  {name:"Carrot",image:"carrot.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
  {name:"Cabbage",image:"cabbage.png",origin:"France",grows:"As a leafy head above the ground",clue:"This leafy vegetable forms a tight round head.",group:"brassica-head"},
  {name:"Brussels Sprouts",image:"brussels-sprouts.png",origin:"Belgium",grows:"As small leafy buds along a tall stalk",clue:"These miniature cabbages grow in rows along a tall stem.",group:"brassica-head"},
  {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
  {name:"Asian Greens",image:"asian-greens.png",origin:"China",grows:"As leafy plants above the ground",clue:"This group includes leafy vegetables such as bok choy."},
  {name:"Ginger",image:"ginger.png",origin:"Southeast Asia",grows:"As a rhizome underground",clue:"This knobbly underground stem has a warm, spicy flavour."},
  {name:"Chestnut",image:"chestnut.png",origin:"Turkey",grows:"On a tree inside a prickly burr",clue:"This glossy brown nut develops inside a very spiky case."},
  {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant",clue:"When cut, this green pod reveals a star shape and many round seeds."},
  {name:"Onion",image:"onion.png",origin:"Iran",grows:"As a bulb underground",clue:"Peeling this layered bulb can make your eyes water.",group:"onion"},
  {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine or bush above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine above the ground",clue:"This long green squash is also called courgette.",group:"squash"},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks above the ground",clue:"Its sweet yellow kernels grow in rows together on a cob."},
  {name:"Pumpkin",image:"pumpkin.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This large orange fruit grows on a vine and is often used in soup or pie.",group:"squash"},
  {name:"Mushrooms",image:"mushrooms.png",origin:"France",grows:"From fungal networks in soil or compost",clue:"This food is a fungus and often has a cap and a stem."},
  {name:"Leek",image:"leek.png",origin:"Turkey",grows:"As a thick stem with leaves above the ground",clue:"This long, mild member of the onion family has layered white and green leaves.",group:"onion"},
  {name:"Fennel",image:"fennel.png",origin:"Italy",grows:"As a swollen bulb at soil level",clue:"This pale bulb has feathery leaves and a fresh anise-like flavour."},
  {name:"Eschalot",image:"eschalot.png",origin:"Iran",grows:"As a bulb underground",clue:"This small bulb tastes milder and sweeter than a large onion.",group:"onion"},
  {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat its green stalk and tightly packed flower buds.",group:"brassica-head"},
  {name:"Beans",image:"beans.png",origin:"Mexico",grows:"Inside pods on bushy or climbing plants",clue:"These seeds develop together inside long pods."},
  {name:"Choko",image:"choko.png",origin:"Mexico",grows:"On a vigorous climbing vine",clue:"This pale green, pear-shaped vegetable is also called chayote."},
  {name:"Capsicum",image:"capsicum.png",origin:"Mexico",grows:"As hollow fruits on a small bush",clue:"This mild hollow pepper can be green, red, yellow or orange."},
  {name:"Eggplant",image:"eggplant.png",origin:"India",grows:"As fruits on a bushy plant",clue:"This glossy purple vegetable is also known as aubergine."},
  {name:"Witlof",image:"witlof.png",origin:"Belgium",grows:"As a tight pale shoot grown from a root",clue:"This pale, slightly bitter leaf is also called Belgian endive."},
  {name:"Turnip",image:"turnip.png",origin:"Afghanistan",grows:"As a swollen root underground",clue:"This round root can have a white body and a purple top."},
  {name:"Sweet Potato",image:"sweet-potato.png",origin:"Peru",grows:"As a storage root underground",clue:"This sweet orange or cream-coloured root grows beneath the soil."},
  {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
  {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"}
  ].map(food => ({
  ...food,
  image: `assets/cards/autumn/${food.image}`
}));
