window.YUMMY_QUESTIONS = window.YUMMY_QUESTIONS || {};

window.YUMMY_QUESTIONS.spring = [
     {name:"Zucchini Flower",image:"zucchini-flower.png",origin:"Italy",grows:"On a vine, above the ground",clue:"This edible yellow flower grows on a zucchini plant.",group:"zucchini"},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine, above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks, above the ground",clue:"Its sweet yellow kernels grow together on a cob."},
  {name:"Peas",image:"peas.png",origin:"Turkey",grows:"Inside pods on climbing vines",clue:"These small green seeds grow together inside a pod."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine, above the ground",clue:"This long green vegetable is also called courgette.",group:"zucchini"},
  {name:"Watercress",image:"watercress.png",origin:"England",grows:"In shallow, flowing water",clue:"This peppery leafy green naturally grows beside clean streams."},
  {name:"Shallot",image:"shallot.png",origin:"Iran",grows:"As a bulb underground",clue:"This small bulb tastes milder and sweeter than an onion.",group:"onion"},
  {name:"Spring Onion",image:"spring-onion.png",origin:"China",grows:"As a small bulb underground with leaves above",clue:"This onion has a long green top and a slender white base.",group:"onion"},
  {name:"Mushrooms",image:"mushrooms.png",origin:"France",grows:"From fungal networks in soil or compost",clue:"This food is a fungus and often has a cap and a stem."},
  {name:"Globe Artichoke",image:"globe-artichoke.png",origin:"Italy",grows:"As a flower bud above the ground",clue:"We eat the unopened flower bud and the soft heart inside."},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is a common base for salads."},
  {name:"Garlic",image:"garlic.png",origin:"Kazakhstan",grows:"As a bulb underground",clue:"This strong-smelling bulb is made of several cloves."},
  {name:"Chillies",image:"chillies.png",origin:"Mexico",grows:"On a small bush above the ground",clue:"These colourful peppers can make food taste very hot."},
  {name:"Green Beans",image:"green-beans.png",origin:"Mexico",grows:"In pods on climbing or bushy plants",clue:"The long green pod is eaten while it is still young.",group:"beans"},
  {name:"Broad Beans",image:"broad-beans.png",origin:"Egypt",grows:"Inside thick pods above the ground",clue:"These large, flat beans are also known as fava beans.",group:"beans"},
  {name:"Asian Greens",image:"asian-greens.png",origin:"China",grows:"As leafy plants above the ground",clue:"This group includes leafy vegetables such as bok choy."},
  {name:"Asparagus",image:"asparagus.png",origin:"Greece",grows:"As spears rising from underground crowns",clue:"Its tender green spears push straight up through the soil."},
  {name:"Beetroot",image:"beetroot.png",origin:"Italy",grows:"As a swollen root underground",clue:"This deep red root can stain your hands when it is cut."},
  {name:"Carrots",image:"carrots.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
  {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
  {name:"Potatoes",image:"potatoes.png",origin:"Peru",grows:"As tubers underground",clue:"These starchy tubers grow beneath the soil."},
  {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"},
  {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft, dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping vine above the ground",clue:"This cool, crisp food has watery flesh and is often sliced for salads."},
  {name:"Green Onion",image:"green-onion.png",origin:"China",grows:"As a small bulb underground with leaves above",clue:"Its long green leaves have a mild onion flavour.",group:"onion"},
  {name:"Loquat",image:"loquat.png",origin:"China",grows:"In clusters on a tree",clue:"This small orange fruit has several large brown seeds."},
  {name:"Cherries",image:"cherries.png",origin:"Turkey",grows:"On a tree",clue:"These small stone fruits often grow in pairs on long stems."},
  {name:"Boysenberry",image:"boysenberry.png",origin:"United States",grows:"On trailing canes above the ground",clue:"This dark berry is a hybrid related to raspberries and blackberries.",group:"cane-berries"},
  {name:"Blackberry",image:"blackberry.png",origin:"United Kingdom",grows:"On thorny canes above the ground",clue:"This dark fruit is made of many small juicy sections.",group:"cane-berries"},
  {name:"Passionfruit",image:"passionfruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its wrinkled skin are many seeds in fragrant pulp."},
  {name:"Melon",image:"melon.png",origin:"Iran",grows:"On a creeping vine along the ground",clue:"This sweet round fruit has juicy flesh and many seeds in the centre.",group:"melon"},
  {name:"Mango",image:"mango.png",origin:"India",grows:"On a tree",clue:"This tropical fruit has sweet golden flesh around one large stone."},
  {name:"Blueberry",image:"blueberry.png",origin:"United States",grows:"In clusters on a bush",clue:"These small blue fruits grow together on shrubs."},
  {name:"Rockmelon",image:"rockmelon.png",origin:"Iran",grows:"On a creeping vine along the ground",clue:"This melon has netted skin and sweet orange flesh.",group:"melon"},
  {name:"Pineapple",image:"pineapple.png",origin:"Brazil",grows:"On a low plant above the ground",clue:"This tropical fruit has spiky leaves and rough patterned skin."},
  {name:"Papaw",image:"papaw.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"In Australia, this is a common name for the large tropical papaya.",group:"papaya"},
  {name:"Papaya",image:"papaya.png",origin:"Mexico",grows:"On the trunk of a tall plant",clue:"This tropical fruit has orange flesh and many black seeds.",group:"papaya"},
  {name:"Mulberry",image:"mulberry.png",origin:"China",grows:"On a tree",clue:"This long, bumpy berry grows on the same tree loved by silkworms."},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
  {name:"Grapefruit",image:"grapefruit-1.png",origin:"Barbados",grows:"On a tree",clue:"This large citrus fruit can taste both tart and slightly bitter."},
  {name:"Apples",image:"apples.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp round fruit grows on a deciduous tree."},
  {name:"Lemons",image:"lemons.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice."},
  {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat this vegetable's green stalk and tightly packed flower buds.",group:"brassica-head"},
  {name:"Mandarins",image:"mandarins.png",origin:"China",grows:"On a tree",clue:"This small citrus fruit has loose skin that is easy to peel.",group:"citrus"},
  {name:"Oranges",image:"oranges.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
  {name:"Pomelo",image:"pomelo.png",origin:"Malaysia",grows:"On a tree",clue:"This is the largest citrus fruit and has a very thick rind.",group:"citrus"},
  {name:"Strawberry",image:"strawberry.png",origin:"France",grows:"On low plants close to the ground",clue:"This red fruit carries its tiny seeds on the outside."},
  {name:"Tangelos",image:"tangelos.png",origin:"United States",grows:"On a tree",clue:"This citrus is a cross between a mandarin and a grapefruit or pomelo.",group:"citrus"},
  {name:"Blood Orange",image:"blood-orange.png",origin:"Italy",grows:"On a tree",clue:"This orange has unusually deep red flesh inside.",group:"citrus"}
  ].map(food => ({
  ...food,
  image: `assets/cards/spring/${food.image}`
}));

