window.YUMMY_QUESTIONS = window.YUMMY_QUESTIONS || {};

window.YUMMY_QUESTIONS.summer = [
     {name:"Blackberry",image:"blackberry.png",origin:"United Kingdom",grows:"On thorny canes above the ground",clue:"This dark berry is made of many small juicy sections.",group:"cane-berries"},
  {name:"Blueberry",image:"blueberry.png",origin:"United States",grows:"In clusters on a bush",clue:"These small blue fruits grow in clusters on woody shrubs."},
  {name:"Passion Fruit",image:"passion-fruit-1.png",origin:"Brazil",grows:"On a climbing vine",clue:"This fragrant tropical fruit contains many seeds in juicy pulp.",group:"passion-fruit"},
  {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
  {name:"Passion Fruit",image:"passion-fruit-2.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its thick skin are many crunchy seeds surrounded by fragrant pulp.",group:"passion-fruit"},
  {name:"Berries",image:"berries.png",origin:"France",grows:"On low plants or canes above the ground",clue:"This card shows a mixed group of small, colourful, juicy fruits.",group:"cane-berries"},
  {name:"Rambutans",image:"rambutans.png",origin:"Malaysia",grows:"In clusters on a tropical tree",clue:"These tropical fruits have red skin covered with soft hair-like spines."},
  {name:"Prickly Pears",image:"prickly-pears.png",origin:"Mexico",grows:"On the pads of a cactus",clue:"These fruits grow on a cactus and must be handled carefully because of tiny spines."},
  {name:"Plums",image:"plums.png",origin:"China",grows:"On a tree",clue:"These smooth-skinned stone fruits can be purple, red, yellow or green.",group:"stone-fruit"},
  {name:"Peach",image:"peach.png",origin:"China",grows:"On a tree",clue:"This sweet stone fruit is famous for its soft, fuzzy skin.",group:"stone-fruit"},
  {name:"Nectarines",image:"nectarines.png",origin:"China",grows:"On a tree",clue:"These stone fruits resemble peaches but have smooth skin.",group:"stone-fruit"},
  {name:"Mangosteens",image:"mangosteens.png",origin:"Indonesia",grows:"On a tropical evergreen tree",clue:"A thick purple rind protects the soft white segments inside."},
  {name:"Lychees",image:"lychees.png",origin:"China",grows:"In clusters on an evergreen tree",clue:"These small fruits have rough red skin and translucent white flesh."},
  {name:"Limes",image:"limes.png",origin:"Malaysia",grows:"On a small citrus tree",clue:"These small green citrus fruits have sharply sour juice."},
  {name:"Raspberry",image:"raspberry.png",origin:"Turkey",grows:"On thorny or bristly canes above the ground",clue:"This soft berry is made of many tiny red sections and has a hollow centre.",group:"cane-berries"},
  {name:"Grapes",image:"grapes.png",origin:"Georgia",grows:"In bunches on a woody vine",clue:"These round fruits grow together in bunches and can be dried into raisins."},
  {name:"Figs",image:"figs.png",origin:"Turkey",grows:"On a tree",clue:"This soft fruit has many tiny seeds and a sweet, jam-like centre."},
  {name:"Currants",image:"currants.png",origin:"Netherlands",grows:"In strings of small berries on a bush",clue:"These tiny red, black or white berries hang in clusters from shrubs."},
  {name:"Apricot",image:"apricot.png",origin:"China",grows:"On a tree",clue:"This small orange stone fruit has soft flesh and a slightly tart taste.",group:"stone-fruit"},
  {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant above the ground",clue:"When cut, this long green pod reveals a star shape and many round seeds."},
  {name:"Sweet Onion",image:"sweet-onion.png",origin:"Iran",grows:"As a bulb underground",clue:"This round bulb has a mild flavour and usually causes fewer tears than a strong onion.",group:"onion"},
  {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
  {name:"Tomato",image:"tomato.png",origin:"Mexico",grows:"On a vine or bush above the ground",clue:"This juicy red food is used in salads, sauces and pizza."},
  {name:"Zucchini",image:"zucchini.png",origin:"Italy",grows:"On a low vine above the ground",clue:"This long green summer squash is also called courgette."},
  {name:"Watercress",image:"watercress.png",origin:"England",grows:"In shallow, clean flowing water",clue:"This peppery leafy green naturally grows beside streams."},
  {name:"Sweet Corn",image:"sweet-corn.png",origin:"Mexico",grows:"On tall stalks above the ground",clue:"Its sweet yellow kernels grow in rows together on a cob."},
  {name:"Green Onion",image:"green-onion.png",origin:"China",grows:"As a small bulb underground with green leaves above",clue:"This onion has long hollow green leaves and a slender white base.",group:"onion"},
  {name:"Peas",image:"peas.png",origin:"Turkey",grows:"Inside pods on climbing vines",clue:"These small round seeds grow together inside a green pod.",group:"peas"},
  {name:"Lettuce",image:"lettuce.png",origin:"Egypt",grows:"As leaves above the ground",clue:"This crisp leafy vegetable is commonly used as the base of a salad."},
  {name:"Cucumber",image:"cucumber.png",origin:"India",grows:"On a creeping or climbing vine above the ground",clue:"This long green food has cool, watery flesh and many soft seeds."},
  {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks of this plant are the part most often eaten."},
  {name:"Butter Bean",image:"butter-bean.png",origin:"Peru",grows:"Inside pods on a bush or climbing vine",clue:"This large, flat, creamy bean is also known as a lima bean.",group:"beans"},
  {name:"Green Beans",image:"green-beans.png",origin:"Mexico",grows:"In pods on bushy or climbing plants",clue:"The entire long green pod is eaten while it is still young.",group:"beans"},
  {name:"Asparagus",image:"asparagus.png",origin:"Greece",grows:"As spears rising from underground crowns",clue:"Its tender green spears push straight up through the soil."},
  {name:"Squash",image:"squash.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This food grows on a spreading vine and may have a hard or soft rind."},
  {name:"Sugar Snap Peas",image:"sugar-snap-peas.png",origin:"United States",grows:"Inside edible pods on climbing vines",clue:"Both the crisp sweet pod and the round peas inside can be eaten.",group:"peas"},
  {name:"Choko",image:"choko.png",origin:"Mexico",grows:"On a vigorous climbing vine",clue:"This pale green, pear-shaped vegetable is also called chayote."},
  {name:"Snake Beans",image:"snake-beans.png",origin:"India",grows:"As very long pods on climbing vines",clue:"These beans form unusually long, thin pods that can curl like a snake.",group:"beans"},
  {name:"Radish",image:"radish.png",origin:"China",grows:"As a swollen root underground",clue:"This crisp, peppery root is often round and red with leaves above the soil."},
  {name:"Flat Beans",image:"flat-beans.png",origin:"Italy",grows:"As broad pods on climbing or bushy plants",clue:"These beans have wide, flattened pods rather than thin round ones.",group:"beans"},
  {name:"Capsicum",image:"capsicum.png",origin:"Mexico",grows:"As hollow fruits on a small bush",clue:"This mild, hollow pepper can be green, red, yellow or orange."},
  {name:"Eggplant",image:"eggplant.png",origin:"India",grows:"As fruits on a bushy plant above the ground",clue:"This glossy purple vegetable is also known as aubergine."}
  ].map(food => ({
  ...food,
  image: `assets/cards/summer/${food.image}`
}));

