window.YUMMY_QUESTIONS = window.YUMMY_QUESTIONS || {};

window.YUMMY_QUESTIONS.winter = [
      {name:"Leeks",image:"leeks.png",origin:"Turkey",grows:"As a thick stem with leaves above the ground",clue:"This long, mild member of the onion family has layered white and green leaves.",group:"onion"},
    {name:"Apple",image:"apple.png",origin:"Kazakhstan",grows:"On a tree",clue:"This crisp fruit grows on a tree and can be red, green or yellow."},
    {name:"Artichoke",image:"artichoke.png",origin:"Italy",grows:"As an unopened flower bud above the ground",clue:"We eat the tender heart and the soft bases of this unopened flower bud."},
    {name:"Avocado",image:"avocado.png",origin:"Mexico",grows:"On a tree",clue:"This creamy green fruit has one very large seed."},
    {name:"Banana",image:"banana.png",origin:"Papua New Guinea",grows:"In hanging bunches on a large herb",clue:"This curved fruit grows in hands within a large hanging bunch."},
    {name:"Beetroot",image:"beetroot.png",origin:"Italy",grows:"As a swollen root underground",clue:"This deep red root can stain your hands when it is cut."},
    {name:"Broccoli",image:"broccoli.png",origin:"Italy",grows:"As flower heads above the ground",clue:"We eat this vegetable's green stalk and tightly packed flower buds.",group:"brassica-head"},
    {name:"Brussels Sprout",image:"brussels-sprout.png",origin:"Belgium",grows:"As small leafy buds along a tall stalk",clue:"These miniature cabbages grow in rows along a tall stem.",group:"brassica-head"},
    {name:"Cabbage",image:"cabbage.png",origin:"France",grows:"As a leafy head above the ground",clue:"This leafy vegetable forms a tight round head and is often used in slaws and soups.",group:"brassica-head"},
    {name:"Carrot",image:"carrot.png",origin:"Iran",grows:"As a root underground",clue:"This crunchy orange root has feathery green leaves above it."},
    {name:"Cauliflower",image:"cauliflower.png",origin:"Cyprus",grows:"As a flower head above the ground",clue:"Its tightly packed white flower buds form a large head.",group:"brassica-head"},
    {name:"Celeriac",image:"celeriac.png",origin:"Italy",grows:"As a swollen stem just below the soil",clue:"This knobbly pale root has a celery-like flavour."},
    {name:"Celery",image:"celery.png",origin:"Italy",grows:"As thick leaf stalks above the ground",clue:"The crisp pale-green stalks of this plant are the part most often eaten."},
    {name:"Cumquat",image:"cumquat.png",origin:"China",grows:"On a small citrus tree",clue:"This tiny oval citrus fruit can be eaten whole, including its sweet peel.",group:"citrus"},
    {name:"Custard Apple",image:"custard-apple.png",origin:"Peru",grows:"On a small tropical tree",clue:"This knobbly fruit has soft, creamy flesh with a custard-like texture."},
    {name:"Fennel",image:"fennel.png",origin:"Italy",grows:"As a swollen bulb at soil level",clue:"This pale bulb has feathery leaves and a fresh anise-like flavour."},
    {name:"Grapefruit",image:"grapefruit.png",origin:"Barbados",grows:"On a tree",clue:"This large citrus fruit can taste both tart and slightly bitter.",group:"citrus"},
    {name:"Jerusalem Artichokes",image:"jerusalem-artichokes.png",origin:"Canada",grows:"As tubers underground",clue:"These knobbly underground tubers are unrelated to globe artichokes."},
    {name:"Kiwi",image:"kiwi.png",origin:"China",grows:"On a climbing vine",clue:"This fuzzy brown fruit has bright green flesh and many tiny black seeds."},
    {name:"Kohlrabi",image:"kohlrabi.png",origin:"Germany",grows:"As a swollen stem above the soil",clue:"This round vegetable is a swollen stem with leaves sprouting from it."},
    {name:"Sweet Potato",image:"sweet-potato.png",origin:"Peru",grows:"As a storage root underground",clue:"This sweet orange or cream-coloured root grows beneath the soil."},
    {name:"Lemon",image:"lemon.png",origin:"India",grows:"On a tree",clue:"This yellow citrus fruit is famous for its sour juice.",group:"citrus"},
    {name:"Mandarin",image:"mandarin.png",origin:"China",grows:"On a tree",clue:"This small citrus fruit has loose skin that is easy to peel.",group:"citrus"},
    {name:"Nashi",image:"nashi.png",origin:"China",grows:"On a tree",clue:"This round Asian pear is crisp and juicy, like an apple."},
    {name:"Okra",image:"okra.png",origin:"Ethiopia",grows:"As pods on an upright plant above the ground",clue:"When cut, this long green pod reveals a star shape and many round seeds."},
    {name:"Olives",image:"olives.png",origin:"Turkey",grows:"In clusters on an evergreen tree",clue:"These small fruits grow on trees and are pressed to make oil."},
    {name:"Onion",image:"onion.png",origin:"Iran",grows:"As a bulb underground",clue:"Peeling this layered bulb can make your eyes water.",group:"onion"},
    {name:"Parsnip",image:"parsnip.png",origin:"Italy",grows:"As a tapered root underground",clue:"This pale root looks like a carrot but has a sweeter, nuttier flavour."},
    {name:"Passion Fruit",image:"passion-fruit.png",origin:"Brazil",grows:"On a climbing vine",clue:"Inside its wrinkled skin are many seeds in fragrant pulp."},
    {name:"Pear",image:"pear.png",origin:"Georgia",grows:"On a tree",clue:"This sweet fruit is wider at the bottom and narrower near its stem."},
    {name:"Pomelo",image:"pomelo.png",origin:"Malaysia",grows:"On a tree",clue:"This is the largest citrus fruit and has a very thick rind.",group:"citrus"},
    {name:"Potato",image:"potato.png",origin:"Peru",grows:"As tubers underground",clue:"This starchy food develops beneath the soil on underground stems."},
    {name:"Pumpkin",image:"pumpkin.png",origin:"Mexico",grows:"On a creeping vine along the ground",clue:"This large orange fruit grows on a vine and is often used in soup or pie."},
    {name:"Quince",image:"quince.png",origin:"Iran",grows:"On a small tree",clue:"This fragrant yellow fruit looks like a lumpy pear and is usually cooked."},
    {name:"Rhubarb",image:"rhubarb.png",origin:"China",grows:"As thick stalks above the ground",clue:"Only the crisp stalks of this plant are eaten, usually after cooking."},
    {name:"Orange",image:"orange.png",origin:"China",grows:"On a tree",clue:"This round citrus fruit shares its name with its colour.",group:"citrus"},
    {name:"Silverbeet",image:"silverbeet.png",origin:"Italy",grows:"As leafy stalks above the ground",clue:"This leafy vegetable has broad leaves and thick pale stalks.",group:"leafy-greens"},
    {name:"Spinach",image:"spinach.png",origin:"Iran",grows:"As leaves above the ground",clue:"This soft, dark-green leaf can be eaten raw or cooked.",group:"leafy-greens"},
    {name:"Strawberry",image:"strawberry.png",origin:"France",grows:"On low plants close to the ground",clue:"This red fruit carries its tiny seeds on the outside."},
    {name:"Swede",image:"swede.png",origin:"Sweden",grows:"As a swollen root underground",clue:"This round yellow-fleshed root is also called rutabaga."},
    {name:"Turnip",image:"turnip.png",origin:"Afghanistan",grows:"As a swollen root underground",clue:"This round root can have a white body and a purple top."},
    {name:"Witlof",image:"witlof.png",origin:"Belgium",grows:"As a tight pale shoot grown from a root",clue:"This pale, slightly bitter leaf is also called Belgian endive."},
    {name:"Tangelos",image:"tangelos.png",origin:"United States",grows:"On a tree",clue:"This citrus is a cross between a mandarin and a grapefruit or pomelo.",group:"citrus"}
    ].map(food => ({
  ...food,
  image: `assets/cards/winter/${food.image}`
}));
